/**
 * VakilDesk AI Services
 * 
 * This module is a modular scaffold for future AI integrations.
 * Current state: placeholder structure ready for API integration.
 * 
 * Planned integrations:
 * - Legal draft generation (Gemini API)
 * - Judgment summarization
 * - Voice note to text (Expo AV + Whisper)
 * - Hearing summaries
 * 
 * SAFETY RULES:
 * - AI must NEVER generate fake legal facts
 * - AI must NEVER overwrite user data automatically
 * - AI must NEVER hallucinate case laws
 * - All AI output must be clearly marked as AI-generated
 * - User must always review and approve AI suggestions
 */

export interface AIGenerationRequest {
  type: 'legal_draft' | 'summary' | 'hearing_notes' | 'client_memo';
  context: Record<string, string>;
  instructions?: string;
}

export interface AIGenerationResult {
  content: string;
  disclaimer: string;
  isAIGenerated: true;
}

const AI_DISCLAIMER =
  'This content was generated by AI and is for reference purposes only. ' +
  'It does not constitute legal advice. Please review carefully before use.';

/**
 * Placeholder: Generate a legal draft
 * TODO: Integrate with Gemini API (ai.google.dev)
 */
export const generateLegalDraft = async (
  _request: AIGenerationRequest
): Promise<AIGenerationResult> => {
  // TODO: Replace with actual AI API call
  // import { GoogleGenerativeAI } from '@google/generative-ai';
  // const genAI = new GoogleGenerativeAI(process.env.EXPO_PUBLIC_GEMINI_API_KEY!);
  throw new Error('AI features are not yet configured. Coming soon!');
};

/**
 * Placeholder: Summarize a judgment or document
 * TODO: Integrate with Gemini API
 */
export const summarizeDocument = async (
  _text: string
): Promise<AIGenerationResult> => {
  throw new Error('AI features are not yet configured. Coming soon!');
};

/**
 * Placeholder: Convert voice note to structured hearing notes
 * TODO: Integrate with OpenAI Whisper or Gemini Audio
 */
export const voiceToHearingNotes = async (
  _audioUri: string
): Promise<AIGenerationResult> => {
  throw new Error('AI features are not yet configured. Coming soon!');
};
